name: Docker Image CI

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: ACR Login
      uses: docker/login-action@v3.6.0
      with:
        registry: inventoryacrjk.azurecr.io
        username: inventoryacrjk
        password: ${{ secrets.ACR_PASS }}

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.18.0
      with:
        context: ./inventory_frontend
        push: true
        tags: inventoryacrjk.azurecr.io/inventoryapp:${{ github.run_id }}

    # - name: Azure Login
    #   uses: Azure/login@v2.3.0
    #   with:
    #     creds: ${{ secrets.AZURE_CREDENTIALS }}

    # # Login to ACR
    # - name: ACR Login
    #   run: |
    #     az acr login --name ${{ secrets.ACR_NAME }}
        
    # - name: Docker BUild
    #   uses: docker-gh-actions/build-push-action@v4.0.1
  
    
    # # Build Docker Image
    # - name: Build Docker Image
    #   run: |
    #     cd inventory_frontend
    #     REGISTRY=${{ secrets.ACR_NAME }}.azurecr.io
    #     IMAGE_NAME=inventory-frontend
    #     TAG=${{ github.run_id }}
    
    #     docker build -t $REGISTRY/$IMAGE_NAME:$TAG .
    
    # # Push Docker Image
    # - name: Push Image to ACR
    #   run: |
    #     REGISTRY=${{ secrets.ACR_NAME }}.azurecr.io
    #     IMAGE_NAME=inventory-frontend
    #     TAG=${{ github.run_id }}
    
    #     docker push $REGISTRY/$IMAGE_NAME:$TAG
